name: geof212env
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.8    # Python version 3.8
    - cartopy       # Geographic plotting toolkit
    - jupyter       # Jupyter federation architecture
    - jupyterlab    # Jupyter Lab environment
    - matplotlib    # 2D plotting library
    - netcdf4       # Wrapper for netcdf4
    - numpy         # N-d array and numerics
    - xarray        # N-d labeled array library
    - ipykernel     # install python env as jupyter kernel